#!/usr/bin/env python3
"""Render a nutrition/science infographic from a compact JSON spec.

This script is intentionally template-driven rather than model-driven: Codex (the
agent) writes or edits the JSON/spec and this renderer deterministically produces
a clean PNG. It supports Chinese text when a CJK font is installed.
"""
from __future__ import annotations

import argparse
import json
import math
import os
from pathlib import Path
from typing import Any, Dict, Iterable, List, Tuple

from PIL import Image, ImageDraw, ImageFont

Color = Tuple[int, int, int]

PALETTE: Dict[str, Color] = {
    "cream": (255, 249, 239),
    "ink": (40, 48, 55),
    "muted": (96, 108, 116),
    "green": (82, 171, 111),
    "leaf": (45, 137, 87),
    "blue": (78, 145, 209),
    "orange": (238, 150, 75),
    "red": (225, 94, 84),
    "purple": (142, 113, 202),
    "yellow": (242, 196, 83),
    "card": (255, 255, 255),
    "line": (224, 229, 232),
}

DEFAULT_SPEC: Dict[str, Any] = {
    "title": "一餐营养结构示例",
    "subtitle": "自动生成的营养学信息图 · 仅作科普展示",
    "theme": "green",
    "plate": [
        {"label": "蔬菜", "value": 40, "color": "green"},
        {"label": "优质蛋白", "value": 25, "color": "orange"},
        {"label": "全谷物", "value": 25, "color": "yellow"},
        {"label": "健康脂肪", "value": 10, "color": "blue"},
    ],
    "metrics": [
        {"label": "能量", "value": "520", "unit": "kcal", "note": "约一餐"},
        {"label": "蛋白质", "value": "31", "unit": "g", "note": "肌肉与饱腹"},
        {"label": "膳食纤维", "value": "12", "unit": "g", "note": "肠道友好"},
    ],
    "bars": [
        {"label": "碳水", "value": 45, "target": 55, "unit": "%", "color": "yellow"},
        {"label": "蛋白质", "value": 28, "target": 25, "unit": "%", "color": "orange"},
        {"label": "脂肪", "value": 27, "target": 30, "unit": "%", "color": "blue"},
    ],
    "tips": [
        "先保证蔬菜和蛋白质，再补主食。",
        "把含糖饮料换成水或无糖茶。",
        "慢性病、孕期或特殊人群请遵医嘱。",
    ],
    "footer": "Generated by LingTai nutrition-infographic skill",
}


def parse_color(value: Any, default: Color = PALETTE["green"]) -> Color:
    if isinstance(value, str):
        if value in PALETTE:
            return PALETTE[value]
        s = value.strip().lstrip("#")
        if len(s) == 6:
            try:
                return tuple(int(s[i : i + 2], 16) for i in (0, 2, 4))  # type: ignore[return-value]
            except ValueError:
                return default
    if isinstance(value, (list, tuple)) and len(value) == 3:
        try:
            return tuple(max(0, min(255, int(x))) for x in value)  # type: ignore[return-value]
        except Exception:
            return default
    return default


def find_font(candidates: Iterable[str], size: int) -> ImageFont.FreeTypeFont | ImageFont.ImageFont:
    paths: List[str] = []
    for env in ("NUTRITION_FONT", "FONT_PATH"):
        p = os.environ.get(env)
        if p:
            paths.append(p)
    paths.extend(candidates)
    paths.extend(
        [
            # macOS CJK fonts. PingFang may be hidden behind font collections on
            # some systems, so prefer the concrete STHeiti / Hiragino paths that
            # are commonly present and known to cover Chinese glyphs.
            "/System/Library/Fonts/STHeiti Medium.ttc",
            "/System/Library/Fonts/STHeiti Light.ttc",
            "/System/Library/Fonts/Hiragino Sans GB.ttc",
            "/System/Library/Fonts/Supplemental/Arial Unicode.ttf",
            "/Library/Fonts/Arial Unicode.ttf",
            "/System/Library/Fonts/PingFang.ttc",
            # Linux CJK fonts.
            "/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc",
            "/usr/share/fonts/truetype/noto/NotoSansCJK-Regular.ttc",
            "/usr/share/fonts/opentype/noto/NotoSansCJK-Bold.ttc",
            "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
        ]
    )
    for path in paths:
        if path and Path(path).exists():
            try:
                return ImageFont.truetype(path, size=size)
            except Exception:
                pass
    return ImageFont.load_default()


def font(size: int, bold: bool = False) -> ImageFont.FreeTypeFont | ImageFont.ImageFont:
    # Prefer CJK-capable fonts even for Latin text; otherwise mixed Chinese/English
    # labels can render as tofu boxes when Arial/DejaVu is chosen first.
    return find_font(
        [
            "/System/Library/Fonts/STHeiti Medium.ttc" if bold else "/System/Library/Fonts/STHeiti Light.ttc",
            "/System/Library/Fonts/Hiragino Sans GB.ttc",
            "/System/Library/Fonts/Supplemental/Arial Unicode.ttf",
            "/usr/share/fonts/opentype/noto/NotoSansCJK-Bold.ttc" if bold else "/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc",
            "/usr/share/fonts/truetype/noto/NotoSansCJK-Regular.ttc",
            "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf" if bold else "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
        ],
        size,
    )


def text_size(draw: ImageDraw.ImageDraw, text: str, fnt: ImageFont.ImageFont) -> Tuple[int, int]:
    box = draw.textbbox((0, 0), text, font=fnt)
    return box[2] - box[0], box[3] - box[1]


def draw_wrapped(
    draw: ImageDraw.ImageDraw,
    xy: Tuple[int, int],
    text: str,
    fnt: ImageFont.ImageFont,
    fill: Color,
    max_width: int,
    line_gap: int = 8,
) -> int:
    x, y = xy
    if not text:
        return y
    # CJK-friendly greedy wrapping: split spaces where possible, otherwise char-by-char.
    chunks = text.split(" ") if " " in text else list(text)
    lines: List[str] = []
    cur = ""
    sep = " " if " " in text else ""
    for chunk in chunks:
        trial = chunk if not cur else cur + sep + chunk
        if text_size(draw, trial, fnt)[0] <= max_width:
            cur = trial
        else:
            if cur:
                lines.append(cur)
            cur = chunk
    if cur:
        lines.append(cur)
    for line in lines:
        draw.text((x, y), line, font=fnt, fill=fill)
        y += text_size(draw, line, fnt)[1] + line_gap
    return y


def lighten(c: Color, amount: float = 0.18) -> Color:
    return tuple(int(v + (255 - v) * amount) for v in c)  # type: ignore[return-value]


def draw_card(draw: ImageDraw.ImageDraw, box: Tuple[int, int, int, int], radius: int = 30) -> None:
    shadow = (0, 0, 0, 28)
    # Draw shadow on an RGBA overlay if available via parent image mode.
    x1, y1, x2, y2 = box
    draw.rounded_rectangle((x1 + 4, y1 + 8, x2 + 4, y2 + 8), radius=radius, fill=(231, 222, 205))
    draw.rounded_rectangle(box, radius=radius, fill=PALETTE["card"], outline=PALETTE["line"], width=2)


def draw_plate(draw: ImageDraw.ImageDraw, center: Tuple[int, int], radius: int, plate: List[Dict[str, Any]]) -> None:
    x, y = center
    total = sum(float(p.get("value", 0)) for p in plate) or 1.0
    start = -90.0
    bbox = (x - radius, y - radius, x + radius, y + radius)
    for item in plate:
        value = float(item.get("value", 0))
        angle = 360.0 * value / total
        color = parse_color(item.get("color"), PALETTE["green"])
        draw.pieslice(bbox, start=start, end=start + angle, fill=color, outline=(255, 255, 255), width=5)
        mid = math.radians(start + angle / 2)
        lx = x + math.cos(mid) * radius * 0.60
        ly = y + math.sin(mid) * radius * 0.60
        label = str(item.get("label", ""))
        pct = int(round(100 * value / total))
        f1 = font(30, bold=True)
        f2 = font(22)
        tw, th = text_size(draw, label, f1)
        draw.text((lx - tw / 2, ly - th / 2 - 10), label, font=f1, fill=(255, 255, 255))
        pct_text = f"{pct}%"
        tw2, th2 = text_size(draw, pct_text, f2)
        draw.text((lx - tw2 / 2, ly + 18), pct_text, font=f2, fill=(255, 255, 255))
        start += angle
    draw.ellipse((x - radius - 8, y - radius - 8, x + radius + 8, y + radius + 8), outline=PALETTE["line"], width=4)


def draw_metrics(draw: ImageDraw.ImageDraw, metrics: List[Dict[str, Any]], x: int, y: int, w: int) -> int:
    if not metrics:
        return y
    gap = 20
    cols = min(3, len(metrics))
    card_w = (w - gap * (cols - 1)) // cols
    for i, m in enumerate(metrics[:3]):
        cx = x + i * (card_w + gap)
        draw.rounded_rectangle((cx, y, cx + card_w, y + 150), radius=22, fill=lighten(parse_color(m.get("color"), PALETTE["green"]), 0.78), outline=PALETTE["line"], width=1)
        draw.text((cx + 24, y + 20), str(m.get("label", "")), font=font(26, bold=True), fill=PALETTE["ink"])
        value = str(m.get("value", ""))
        unit = str(m.get("unit", ""))
        draw.text((cx + 24, y + 62), value, font=font(46, bold=True), fill=parse_color(m.get("color"), PALETTE["leaf"]))
        vw, _ = text_size(draw, value, font(46, bold=True))
        draw.text((cx + 32 + vw, y + 80), unit, font=font(24), fill=PALETTE["muted"])
        draw.text((cx + 24, y + 116), str(m.get("note", "")), font=font(20), fill=PALETTE["muted"])
    return y + 170


def draw_bars(draw: ImageDraw.ImageDraw, bars: List[Dict[str, Any]], x: int, y: int, w: int) -> int:
    if not bars:
        return y
    draw.text((x, y), "营养比例 / 目标参考", font=font(30, bold=True), fill=PALETTE["ink"])
    y += 42
    for b in bars:
        label = str(b.get("label", ""))
        value = float(b.get("value", 0))
        target = float(b.get("target", 100)) or 100
        unit = str(b.get("unit", ""))
        color = parse_color(b.get("color"), PALETTE["green"])
        draw.text((x, y), label, font=font(23, bold=True), fill=PALETTE["ink"])
        val_text = f"{value:g}{unit}"
        tw, _ = text_size(draw, val_text, font(22))
        draw.text((x + w - tw, y), val_text, font=font(22), fill=PALETTE["muted"])
        y += 28
        bar_w = w
        # Values are usually percentages; render them against a fixed 0-100
        # scale so 20% visibly differs from 50%. Values above 100 are capped.
        scale = 100.0 if unit == "%" or max(target, value) <= 100 else max(target, value, 1)
        fill_w = max(0, min(bar_w, int(bar_w * value / scale)))
        draw.rounded_rectangle((x, y, x + bar_w, y + 24), radius=12, fill=(237, 241, 242))
        draw.rounded_rectangle((x, y, x + fill_w, y + 24), radius=12, fill=color)
        target_x = x + min(bar_w, int(bar_w * target / scale))
        draw.line((target_x, y - 4, target_x, y + 28), fill=PALETTE["ink"], width=2)
        y += 34
    return y


def render(spec: Dict[str, Any], out_path: Path, width: int = 1400, height: int = 1000) -> None:
    bg = parse_color(spec.get("background"), PALETTE["cream"])
    theme = parse_color(spec.get("theme"), PALETTE["green"])
    img = Image.new("RGB", (width, height), bg)
    draw = ImageDraw.Draw(img)

    margin = 72
    draw.rounded_rectangle((margin, margin, width - margin, height - margin), radius=46, fill=(255, 255, 255), outline=PALETTE["line"], width=2)
    draw.rounded_rectangle((margin, margin, width - margin, margin + 18), radius=12, fill=theme)

    title = str(spec.get("title", DEFAULT_SPEC["title"]))
    subtitle = str(spec.get("subtitle", ""))
    draw.text((margin + 54, margin + 54), title, font=font(54, bold=True), fill=PALETTE["ink"])
    if subtitle:
        draw_wrapped(draw, (margin + 56, margin + 124), subtitle, font(25), PALETTE["muted"], width - 2 * margin - 112, 6)

    plate = spec.get("plate", DEFAULT_SPEC["plate"])
    if isinstance(plate, list) and plate:
        draw_plate(draw, (margin + 320, margin + 420), 230, plate)

    metrics = spec.get("metrics", DEFAULT_SPEC["metrics"])
    right_x = margin + 620
    right_w = width - margin - 54 - right_x
    y = margin + 210
    if isinstance(metrics, list):
        y = draw_metrics(draw, metrics, right_x, y, right_w)

    # Reserve the bottom band for tips so charts never collide with it.
    tips = spec.get("tips", DEFAULT_SPEC["tips"])
    tip_x = margin + 92
    tip_y = height - margin - 205
    tip_w = width - 2 * margin - 184
    bars = spec.get("bars", DEFAULT_SPEC["bars"])
    if isinstance(bars, list):
        max_bars = max(1, min(len(bars), 2 if y + 42 + len(bars) * 62 > tip_y - 18 else len(bars)))
        y = draw_bars(draw, bars[:max_bars], right_x, y + 20, right_w)

    draw.rounded_rectangle((tip_x, tip_y, tip_x + tip_w, tip_y + 140), radius=26, fill=(247, 250, 246), outline=PALETTE["line"], width=1)
    draw.text((tip_x + 28, tip_y + 22), "实用提示", font=font(28, bold=True), fill=theme)
    line_y = tip_y + 66
    if isinstance(tips, list):
        for tip in tips[:3]:
            draw.text((tip_x + 32, line_y), "•", font=font(23, bold=True), fill=theme)
            draw_wrapped(draw, (tip_x + 58, line_y - 2), str(tip), font(22), PALETTE["ink"], tip_w - 90, 2)
            line_y += 30

    footer = str(spec.get("footer", DEFAULT_SPEC["footer"]))
    fw, _ = text_size(draw, footer, font(18))
    draw.text((width - margin - 42 - fw, height - margin - 36), footer, font=font(18), fill=PALETTE["muted"])

    out_path.parent.mkdir(parents=True, exist_ok=True)
    img.save(out_path)


def load_spec(path: str | None) -> Dict[str, Any]:
    if not path:
        return dict(DEFAULT_SPEC)
    with open(path, "r", encoding="utf-8") as f:
        user = json.load(f)
    spec = dict(DEFAULT_SPEC)
    spec.update(user)
    return spec


def main() -> None:
    ap = argparse.ArgumentParser(description="Render a nutrition infographic PNG from JSON.")
    ap.add_argument("--spec", help="Path to JSON spec. If omitted, renders a demo.")
    ap.add_argument("--out", default="nutrition-infographic.png", help="Output PNG path.")
    ap.add_argument("--width", type=int, default=1400)
    ap.add_argument("--height", type=int, default=1000)
    ap.add_argument("--write-demo-spec", help="Write a starter JSON spec and exit.")
    args = ap.parse_args()

    if args.write_demo_spec:
        p = Path(args.write_demo_spec)
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(json.dumps(DEFAULT_SPEC, ensure_ascii=False, indent=2), encoding="utf-8")
        print(f"Wrote demo spec: {p}")
        return

    spec = load_spec(args.spec)
    render(spec, Path(args.out), args.width, args.height)
    print(f"Wrote image: {args.out}")


if __name__ == "__main__":
    main()
